### ISSUE TITLE
Error while achieving external id for node

### ISSUE THREAD

**Issue by pacocuenca** [vmware/nsx-container-plugin-operator#188] opened 2022-05-03 08:49 UTC
### Describe the bug

In a Openshift cluster with 4.8.33 version the nsx-ncp Cluster Operator gets degrade with the message:

Name:         nsx-ncp
Namespace:
Labels:       <none>
Annotations:  nsx-ncp.operator.vmware.com/last-seen-state: {"DaemonsetStates":[],"DeploymentStates":[]}
API Version:  config.openshift.io/v1
Kind:         ClusterOperator
Metadata:
  Creation Timestamp:  2022-04-27T15:29:19Z
  Generation:          1
  Managed Fields:
    API Version:  config.openshift.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:nsx-ncp.operator.vmware.com/last-seen-state:
      f:spec:
      f:status:
        .:
        f:conditions:
        f:extension:
        f:versions:
    Manager:         nsx-ncp-operator
    Operation:       Update
    Time:            2022-04-27T15:57:23Z
  Resource Version:  3892776
  UID:               a9e5ee62-8e2c-4037-b566-8ea111329a42
Spec:
Status:
  Conditions:
    Last Transition Time:  2022-04-29T12:11:36Z
    Message:               Error while achieving external id for node master03.clustername.mydomain.com: no virtual machine matches provider ID 4222262a-b57f-d72c-a573-2508a71243ab and hostname master03.clustername.mydomain.com
Error while achieving external id for node worker01.clustername.mydomain.com: no virtual machine matches provider ID 42225cd2-cd68-c06a-82f0-a226d33d5f9c and hostname worker01.clustername.mydomain.com
Error while achieving external id for node worker02.clustername.mydomain.com: no virtual machine matches provider ID 4222201c-986c-adab-084d-b235397337dd and hostname worker02.clustername.mydomain.com
Error while achieving external id for node infra02.clustername.mydomain.com: no virtual machine matches provider ID 4222d760-3800-0576-2312-5b5e6540de9d and hostname infra02.clustername.mydomain.com
Error while achieving external id for node master02.clustername.mydomain.com: no virtual machine matches provider ID 4222310c-09d1-9f8c-3fe5-6a5f960fae9c and hostname master02.clustername.mydomain.com
Error while achieving external id for node infra03.clustername.mydomain.com: no virtual machine matches provider ID 4222fccb-6c51-2114-f5e3-9cd90ca30626 and hostname infra03.clustername.mydomain.com
Error while achieving external id for node master01.clustername.mydomain.com: no virtual machine matches provider ID 4222f310-e458-4ef6-9f14-5d8fe1ec97ee and hostname master01.clustername.mydomain.com
Error while achieving external id for node infra01.clustername.mydomain.com: no virtual machine matches provider ID 42227e67-b5c1-bf09-1799-63a7c43d13f9 and hostname infra01.clustername.mydomain.com
Error while achieving external id for node worker03.clustername.mydomain.com: no virtual machine matches provider ID 42226b68-3dfc-4a96-67ee-1fb8047b7a24 and hostname worker03.clustername.mydomain.com
    Reason:                ProcessClusterNodeError
    Status:                True
    Type:                  Degraded
    Last Transition Time:  2022-04-27T15:29:19Z
    Status:                True
    Type:                  Upgradeable
    Last Transition Time:  2022-05-03T07:00:11Z
    Status:                False
    Type:                  Progressing
    Last Transition Time:  2022-04-27T15:57:23Z
    Status:                True
    Type:                  Available
  Extension:               <nil>
  Versions:
    Name:     operator
    Version:  0.0.3
Events:       <none>

We have more than 1.000 VMs managed in our NSX-T environmet. Could be a problem with the api usage /api/v1/fabric/virtual-machines inside NCP?

NCP version: 3.2.0.2.19024342

Thanks.

### Reproduction steps

```bash
1. Deploy a Openshift Cluster in a NSX-T environment that is managing more than 1.000 VMs in addition to those of Openshift.
2. Try to get running the cluster operator nsx-ncp
3. See if you get:

NAME                                       VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE
nsx-ncp                                    0.0.3     True        False         True       5d16h

...
```

### Expected behavior

One can expect a non degraded operator.

**Comment by heypnus** [comment] 2022-05-07 15:22
Hi @pacocuenca, how many nodes(VMs) reported `Error while achieving external id`, all 1000+ nodes or a few of them? Could you please provide the accurate numbers of a) all nodes and b) problematic nodes?

**Comment by pacocuenca** [comment] 2022-05-07 15:48
Hello @heypnus, all nodes in the Openshift cluster (9 nodes) are reporting this issue.

**Comment by heypnus** [comment] 2022-05-07 15:56
@pacocuenca You mean the NSX-T is associated with 1000+ vms but only 9 of them are in the openshift cluster? Could you check how many vms are returned from `/api/v1/fabric/virtual-machines`? You can try the following command:
`curl -sku 'username:userpass' -H 'Content-Type: application/json' -X GET https://${NSX_MANAGER_IP}/api/v1/fabric/virtual-machines | jq .result_count`

**Comment by pacocuenca** [comment] 2022-05-07 16:51
@heypnus, yes, the NSX-T is associated with 1000+ vms, but only 9 of them are in the openshift cluster.

The api reports 1694 vms, but when I execute the seccond command to get the nodes I get only 1000 vms (it's the reason that I suspect about the api usage in ncp):

$curl -sku 'username:userpass' -H 'Content-Type: application/json' -X GET https://${NSX_MANAGER_IP}/api/v1/fabric/virtual-machines > vms.output

$ grep external_id vms.output  | wc -l
1000

$ egrep "master|worker|infra" vms.output  | wc -l
0

**Comment by heypnus** [comment] 2022-05-20 03:27
@pacocuenca The root cause is that the code didn't handle the pagination. Ths fix is WIP. Thanks for your report.

**Comment by timdengyun** [comment] 2022-06-13 07:14
@pacocuenca  The fix PR: https://github.com/vmware/nsx-container-plugin-operator/pull/192 is merged.

**Closed by timdengyun** 2022-06-13 07:14 UTC
Labels: bug
