### ISSUE TITLE
Unable to set up Openshift 4.8.14 under NSX-T3.1.3 and NCP 3.2.0.2

### ISSUE THREAD

**Issue by pacocuenca** [vmware/nsx-container-plugin-operator#180] opened 2022-03-15 10:24 UTC
### Describe the bug

Trying to set up a PoC with NCP 3.2.0.2 in a fresh install of OpenShift 4.8.14 allways getting the same failure in nsx-ncp-operator:

2022-03-15T09:57:58.646243042+00:00 stderr F {"level":"info","ts":"2022-03-15T09:57:58.646Z","logger":"controller_configmap","msg":"Received unsupported change","Request.Namespace":"nsx-system-operator","Request.Name":"kube-root-ca.crt"}
2022-03-15T09:57:58.646346514+00:00 stderr F {"level":"info","ts":"2022-03-15T09:57:58.646Z","logger":"controller_configmap","msg":"Reconciling nsx-ncp-operator ConfigMap change","Request.Namespace":"nsx-system-operator","Request.Name":"nsx-ncp-operator-config"}
2022-03-15T09:57:58.646765702+00:00 stderr F {"level":"info","ts":"2022-03-15T09:57:58.646Z","logger":"controller_configmap","msg":"Starting render phase"}
2022-03-15T09:57:58.646990300+00:00 stderr F {"level":"info","ts":"2022-03-15T09:57:58.646Z","logger":"controller_configmap","msg":"Got the manifest dir: ./manifest/openshift4/coreos"}
2022-03-15T09:57:58.653542829+00:00 stderr F {"level":"info","ts":"2022-03-15T09:57:58.653Z","logger":"controller_configmap","msg":"Updated shared info with Nsx Ncp Resources"}
2022-03-15T09:57:58.653621097+00:00 stderr F {"level":"info","ts":"2022-03-15T09:57:58.653Z","logger":"controller_configmap","msg":"nsx-node-agent and nsx-ncp-bootstrap DaemonSet changed"}
2022-03-15T09:57:58.653687386+00:00 stderr F 2022/03/15 09:57:58 reconciling (apiextensions.k8s.io/v1, Kind=CustomResourceDefinition) /nsxerrors.nsx.vmware.com
2022-03-15T09:57:58.664449650+00:00 stderr F 2022/03/15 09:57:58 update was successful
2022-03-15T09:57:58.664589817+00:00 stderr F 2022/03/15 09:57:58 reconciling (apiextensions.k8s.io/v1, Kind=CustomResourceDefinition) /nsxlocks.nsx.vmware.com
2022-03-15T09:57:58.672102043+00:00 stderr F 2022/03/15 09:57:58 update was successful
2022-03-15T09:57:58.672240444+00:00 stderr F 2022/03/15 09:57:58 reconciling (apiextensions.k8s.io/v1, Kind=CustomResourceDefinition) /ncpconfigs.nsx.vmware.com
2022-03-15T09:57:58.679990102+00:00 stderr F 2022/03/15 09:57:58 update was successful
2022-03-15T09:57:58.680175432+00:00 stderr F 2022/03/15 09:57:58 reconciling (/v1, Kind=Namespace) /nsx-system
2022-03-15T09:57:58.686290004+00:00 stderr F 2022/03/15 09:57:58 update was successful
2022-03-15T09:57:58.686445535+00:00 stderr F 2022/03/15 09:57:58 reconciling (/v1, Kind=ServiceAccount) nsx-system/nsx-node-agent-svc-account
2022-03-15T09:57:58.692841174+00:00 stderr F 2022/03/15 09:57:58 update was successful
2022-03-15T09:57:58.693058728+00:00 stderr F 2022/03/15 09:57:58 reconciling (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /nsx-node-agent-cluster-role
2022-03-15T09:57:58.699533880+00:00 stderr F 2022/03/15 09:57:58 update was successful
2022-03-15T09:57:58.699697849+00:00 stderr F 2022/03/15 09:57:58 reconciling (rbac.authorization.k8s.io/v1, Kind=ClusterRoleBinding) /nsx-node-agent-cluster-role-binding
2022-03-15T09:57:58.706387024+00:00 stderr F 2022/03/15 09:57:58 update was successful
2022-03-15T09:57:58.706538469+00:00 stderr F 2022/03/15 09:57:58 reconciling (/v1, Kind=ServiceAccount) nsx-system/ncp-svc-account
2022-03-15T09:57:58.713268752+00:00 stderr F 2022/03/15 09:57:58 update was successful
2022-03-15T09:57:58.713380686+00:00 stderr F 2022/03/15 09:57:58 reconciling (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /ncp-cluster-role
2022-03-15T09:57:58.719786969+00:00 stderr F 2022/03/15 09:57:58 update was successful
2022-03-15T09:57:58.719930597+00:00 stderr F 2022/03/15 09:57:58 reconciling (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /**ncp-patch-role**
2022-03-15T09:57:58.737282124+00:00 stderr F {"level":"error","ts":"2022-03-15T09:57:58.736Z","logger":"controller_configmap","msg":"**could not apply** (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /ncp-patch-role","error":"could not update object (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /ncp-patch-role: clusterroles.rbac.authorization.k8s.io \"ncp-patch-role\" is forbidden: user \"system:serviceaccount:nsx-system-operator:nsx-ncp-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:nsx-system-operator\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"events\"], Verbs:[\"create\" \"get\" \"list\" \"patch\" \"update\" \"delete\"]}","errorVerbose":"clusterroles.rbac.authorization.k8s.io \"ncp-patch-role\" is forbidden: user \"system:serviceaccount:nsx-system-operator:nsx-ncp-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:nsx-system-operator\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"events\"], Verbs:[\"create\" \"get\" \"list\" \"patch\" \"update\" \"delete\"]}\ncould not update object (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /ncp-patch-role\ngithub.com/openshift/cluster-network-operator/pkg/apply.ApplyObject\n\t/home/runner/go/pkg/mod/github.com/openshift/cluster-network-operator@v0.0.0-20200505233431-0c44782d5245/pkg/apply/apply.go:58\ngithub.com/vmware/nsx-container-plugin-operator/pkg/controller/configmap.(*ReconcileConfigMap).Reconcile\n\t/home/runner/work/nsx-container-plugin-operator/nsx-container-plugin-operator/pkg/controller/configmap/configmap_controller.go:495\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/vmware/nsx-container-plugin-operator/pkg/controller/configmap.(*ReconcileConfigMap).Reconcile\n\t/home/runner/work/nsx-container-plugin-operator/nsx-container-plugin-operator/pkg/controller/configmap/configmap_controller.go:496\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88"}
2022-03-15T09:57:58.737688072+00:00 stderr F {"level":"error","ts":"2022-03-15T09:57:58.737Z","logger":"controller-runtime.controller","msg":"Reconciler error","controller":"configmap-controller","request":"nsx-system-operator/nsx-ncp-operator-config","error":"could not update object (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /ncp-patch-role: clusterroles.rbac.authorization.k8s.io \"ncp-patch-role\" is forbidden: user \"system:serviceaccount:nsx-system-operator:nsx-ncp-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:nsx-system-operator\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"events\"], Verbs:[\"create\" \"get\" \"list\" \"patch\" \"update\" \"delete\"]}","errorVerbose":"clusterroles.rbac.authorization.k8s.io \"ncp-patch-role\" is forbidden: user \"system:serviceaccount:nsx-system-operator:nsx-ncp-operator\" (groups=[\"system:serviceaccounts\" \"system:serviceaccounts:nsx-system-operator\" \"system:authenticated\"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[\"\"], Resources:[\"events\"], Verbs:[\"create\" \"get\" \"list\" \"patch\" \"update\" \"delete\"]}\ncould not update object (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /ncp-patch-role\ngithub.com/openshift/cluster-network-operator/pkg/apply.ApplyObject\n\t/home/runner/go/pkg/mod/github.com/openshift/cluster-network-operator@v0.0.0-20200505233431-0c44782d5245/pkg/apply/apply.go:58\ngithub.com/vmware/nsx-container-plugin-operator/pkg/controller/configmap.(*ReconcileConfigMap).Reconcile\n\t/home/runner/work/nsx-container-plugin-operator/nsx-container-plugin-operator/pkg/controller/configmap/configmap_controller.go:495\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.2/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.17.1/pkg/util/wait/wait.go:88"}

### Reproduction steps

```bash
1.Follow all steps in https://github.com/vmware/nsx-container-plugin-operator related to manifest files config
2.Generate ignitions
3. Launch bootstrap and masters
...
```

### Expected behavior

I could expect the cluster to progress with NCP as CNI.

**Comment by timdengyun** [comment] 2022-03-15 11:53
Hi Pacocuenca,

Thanks for raising up this issue, 

2022-03-15T09:57:58.719930597+00:00 stderr F 2022/03/15 09:57:58 reconciling (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /ncp-patch-role
2022-03-15T09:57:58.737282124+00:00 stderr F {"level":"error","ts":"2022-03-15T09:57:58.736Z","logger":"controller_configmap","msg":"could not apply (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /ncp-patch-role","error":"could not update object (rbac.authorization.k8s.io/v1, Kind=ClusterRole) /ncp-patch-role: clusterroles.rbac.authorization.k8s.io "ncp-patch-role" is forbidden: user "system:serviceaccount:nsx-system-operator:nsx-ncp-operator" (groups=["system:serviceaccounts" "system:serviceaccounts:nsx-system-operator" "system:authenticated"]) is attempting to grant RBAC permissions not currently held:\n{APIGroups:[""], Resources:["events"], Verbs:["create" "get" "list" "patch" "update" 

From log above, it looks like it was caused by ncp-patch-role not able to operator events resources. We did change the 
deploy/openshift4/role.yaml in the latest manifest files from PR below:

https://github.com/vmware/nsx-container-plugin-operator/pull/172

I suggest you have a try to apply the latest manifests files, incuduing confimap, ncp-install etc, also apply new role.yaml, I believe your issue will be fixed.  if any more problems, please let us know. Thanks.

**Closed** 2022-03-15 13:13 UTC
Labels: bug
